### PR TITLE
Get rid of gratuitous mem::replace.

### PR DESCRIPTION
**Pull request by Stebalien**
Nittiest of nit picks.

### CODE REVIEW

**Comment by Stebalien** [comment]
Actually, why are you even doing this? Are you trying to avoid dropping the job_sender? If so, this isn't the way to do it. You should use `unsafe { ptr::write(&mut self.job_sender, None) }` or `mem::forget(mem::replace(&mut self.job_sender, None))`.

**Comment by Stebalien** [comment]
Or are you trying to make drop idempotent?

**Comment by Kimundi** [comment]
Ah, seems like the comment explaining that got lost somewhere along the way. I'm not 100% on this myself right now, but this stems from the original scoped v2 proposal and is supposed to drop the field before the type containing it, due there being a change of a deadlock or so.

**Comment by Stebalien** [comment]
I don't think that applies in this case. The only thing I can think of is that if you drop the thread pool while writing to the channel, the channel will block indefinitely. However, that isn't possible here.

**Comment by Kimundi** [comment]
In any case the use of replace is unneeded here, so I'll just merge this, thanks!

**Pull request merged**
